Repository DeepBlueRobotics/lib199, pull requests merged in 2024-05, with the labels that each got.

#70 Link External Javadocs
  build.gradle
Labels: documentation

#61 Add method to MotorErrors.java to check if a CANSparkMax is currently overheated
  src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
Labels: enhancement, Non-Breaking Change

#23 Remove logging support
  src/main/java/org/carlmontrobotics/lib199/logging/DataLog.java
  src/main/java/org/carlmontrobotics/lib199/logging/EventLog.java
  src/main/java/org/carlmontrobotics/lib199/logging/GlobalLogInfo.java
  src/main/java/org/carlmontrobotics/lib199/logging/Log.java
  src/main/java/org/carlmontrobotics/lib199/logging/LogFiles.java
  src/main/java/org/carlmontrobotics/lib199/logging/LogUtils.java
  src/main/java/org/carlmontrobotics/lib199/logging/TimeLog.java
Labels: Breaking Change

#88 Link Phoenix 6 Javadocs
  build.gradle
Labels: documentation
